### ISSUE TITLE
TOO MANY NODES!?!?

### ISSUE THREAD

**Issue by ShayBox** [gilamran/tsc-watch#1]
One problem is this doesn't kill the old process it ran, so if you start a node server it will just start more, not terminating the old ones

**Comment by bookercodes** [comment]
Yeah, I have the same problem 😢

**Comment by ORESoftware** [comment]
@gilamran ....  attention

yeah perhaps `{detached:false}` would be a good option to use here

**Comment by gilamran** [comment]
I've tested it with a very simple `--onSuccess "node timer.js"` and it killed the process.
Can you give an example that will hang the process?
p.s.
What OS are you using?

**Comment by bookercodes** [comment]
For me, the problem happens on macOS (in Visual Studio Code terminal)

**Comment by gilamran** [comment]
@bookercodes What task are you trying to run? can you reproduce it with a simple example?
I also maintain the [fullstack-typescript](https://github.com/gilamran/fullstack-typescript) repo. and I use `tsc-watch` there on an express node app. and it works with no duplications.

I need to understand what's the source of this issue. maybe share a repo. that I can close and view the issue?

**Comment by gilamran** [comment]
a use case was found (`tsc-watch --onSuccess "node --debug=5858 dist/index.js"`)
a fix is on the way

**Comment by gilamran** [comment]
Fixed on version 1.0.6
