### ISSUE TITLE
Is is possible to use the source maps when running the app in the --onSuccess arg?

### ISSUE THREAD

**Issue by heresandyboy** [gilamran/tsc-watch#100]
Hi,

I have been using this for a while now instead of nodemon or ts-node-dev. 
There's one thing I get from the other two that I do not see a way to configure here.

When the app is running, any errors that occur print the path to the JavaScript with tsc-watch, rather than the TypeScript via the source maps like the other two do.

I end up having to switch back to one of the others just to help me debug effectively.

Is it possible to configure tsc-watch to use the source maps when running, or would this be a feature request (or not possible at all)?

**Comment by gilamran** [comment]
I think that this should be doable, tsc-watch is running the typescript compiler after all... 
Do you use source maps in your project? 
Can you share some more information on your setup? 
Maybe an example?

**Comment by gilamran** [comment]
Bump

**Comment by heresandyboy** [comment]
Sorry @gilamran I'm having a very busy couple of days, I'll get back to you tomorrow or at the weekend with some boilerplate

**Comment by gilamran** [comment]
@heresandyboy Thanks!

**Comment by Wizek** [comment]
+1, js line numbers are not remotely as useful as ts ones.

**Comment by Wizek** [comment]
Big update!

`tsc-watch --sourceMap` does work to the extent of outputting `.js.map` files, but I couldn't make node pick these up in my quick attempts.

However! This fully works for me:
```
tsc-watch ./src/index.ts --outDir dist --onSuccess "node --enable-source-maps ./dist/index.js" --inlineSourceMap
```
```
12:21:21 AM - Starting compilation in watch mode...


12:21:24 AM - Found 0 errors. Watching for file changes.

Error
    at Object.<anonymous> (C:\Users\Wizek\sandbox\project-x\dist\index.js:46:7)
        -> C:\Users\Wizek\sandbox\project-x\src\index.ts:12:7
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:776:16)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

I did need to upgrade node from v10. I chose v14, but IIRC as low as v12 could work.

It's still not perfect: I have little use for the js line number, it would be nice if I could hide that somehow, but it's getting there!

**Comment by Wizek** [comment]
Even better update! Look at this perfection:

```
12:25:21 AM - Starting compilation in watch mode...


12:25:25 AM - Found 0 errors. Watching for file changes.

C:\Users\Wizek\sandbox\project-x\src\index.ts:12
throw new Error()
      ^
Error:
    at Object.<anonymous> (C:\Users\Wizek\sandbox\project-x\src\index.ts:12:7)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

Attainable via:

```
tsc-watch ./src/index.ts --outDir dist --onSuccess "node -r source-map-support/register ./dist/index.js" --inlineSourceMap
```

Just remember to `npm i -s source-map-support`, and IIUC this works even with older node versions!
I can hardly contain my excitement. :)

**Comment by gilamran** [comment]
Thanks @Wizek !
