### ISSUE TITLE
On Windows (at least), trying to run tsc-watch --onSuccess via `npm run start` causes it to error.

### ISSUE THREAD

**Issue by Wizek** [gilamran/tsc-watch#102]
package.json:

```json
  "scripts": {
    "start": "tsc-watch --onSuccess 'node ./dist/index.js' --outDir dist ./src/index.ts",
  },
```

Output:

```
11:58:43 PM - Starting compilation in watch mode...

error TS6054: File 'dist/index.js'' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.

11:58:46 PM - Found 1 error. Watching for file changes.
```

In PowerShell, just running 

```ps
> tsc-watch --onSuccess 'node ./dist/index.js' --outDir dist ./src/index.ts
```

Succeeds as expected.

Luckily, this workaround works:

```json
  "scripts": {
    "start": "tsc-watch --onSuccess \"node ./dist/index.js\" --outDir dist ./src/index.ts",
  },
```

But it would be nice not to need it as the error is unintuitive and confusing.

**Comment by Nicholaiii** [comment]
This is not fixed for me by using `--outDir dist`, nor when the tsconfig explicitly has dist as outdir as well.

**Comment by gilamran** [comment]
You must use double quotes to pass arguments to commands
`"start": "tsc-watch --onSuccess \"node ./dist/index.js\" --outDir dist ./src/index.ts"`
