### ISSUE TITLE
tsc-watch when debugging typescript

### ISSUE THREAD

**Issue by alanlivio** [gilamran/tsc-watch#105]
I can find any documentation about use tsc-watch when debug typescript.
Is it possible?

**Comment by gilamran** [comment]
`tsc-watch` is using `tsc` in the background. anything that you can do with typescript you can do with `tsc-watch`
What did you try and couldn't do?

**Comment by alanlivio** [comment]
I do that. 
When using ```tsc-watch --onSuccess "node ./dist/server.js"``` the program is started after change.
I would like to do the same thing when debugging.

**Comment by gilamran** [comment]
How would you do that with the regular `tsc`?

**Comment by gilamran** [comment]
bump

**Comment by rhyek** [comment]
Just do `tsc-watch --onSuccess "node --inspect ./dist/server.js"`
