### ISSUE TITLE
File is a Javascript file. Did you mean to enable the 'allowJs' option?

### ISSUE THREAD

**Issue by sns-sem** [gilamran/tsc-watch#106]
When attempting to run any js file, I am getting the following error:

`error TS6504: File 'build/electron.js' is a JavaScript file. Did you mean to enable the 'allowJs' option?`

`error TS6504: File 'build/app.js' is a JavaScript file. Did you mean to enable the 'allowJs' option?`

The only resource I found about this is [another stackoverflow](https://stackoverflow.com/questions/62943334/tsc-watch-throwing-error-file-dist-index-js-is-a-javascript-file-did-you-me) question with the same problem. I tried global installing (as suggested in the stackoverflow) but it did not fix the problem.

I also have the `allowJs` option enabled in my tsconfig.json.

OS: Windows 10
Node: v12.9.0
TypeScript: v4.0.3
tsc-watch: v4.2.9

Usage, I tried running it with node and electron:
`tsc-watch --onSuccess electron build/electron.js`
`tsc-watch --onSuccess node ./build/app.js`

Same result on both.

**Comment by gilamran** [comment]
What happens when you just run `tsc`?

**Comment by evert** [comment]
I think you need:

     tsc-watch --onSuccess 'node ./build/app.js'

Otherwise only 'node' will be passed to the onSuccess argument, and `./build/app.js` will be treated as the only input file. Passing 1 input file to `tsc` will cause `tsconfig.json` to be ignored.

**Comment by hcgaron** [comment]
I'd like to point out that I can't copy or move files around in the --onSuccess callback.  I have something like:

`tsc-watch --onSuccess 'copy ./dist/MOD/myMod.js ./otherFolder/lib/myMod.js'`

I get the same error as mentioned in the original issue (similarly if I use the mv command).  I am on Windows 10; however, when I've used this similar workflow on Ubuntu (for a different project) I didn't encounter any such issue.

**Comment by gilamran** [comment]
Looks like @evert answered your question.

**Comment by anantakrroy** [comment]
I am trying to run `tsc-watch --onSuccess 'node ./dist/server.js'` in an npm script but keep running into the error
`error TS6054: File 'dist/server.js'' has an unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.` . I have tried enabling `allowJs` and also specified the `outDir` as `dist` in the `tsconfig` file. But nothing seems to work and no `dist` folder is created as well.

**Comment by gilamran** [comment]
@anantakrroy You have to notify `tsc-watch` (Just like in `tsc`) that you are using a project (`tsconfig.json`) by adding `-p`. without it `tsc` thinks that you want to compile the `./dist/server.js`

**Comment by anantakrroy** [comment]
@gilamran Adding `-p` does stop complaining about `js` files, but the build folder (in my case `dist`) is not being created at all.

**Comment by gilamran** [comment]
Can you share an example repo. demonstrating your issue?

**Comment by anantakrroy** [comment]
I have this [repo](https://github.com/anantakrroy/storefront_api) .

**Comment by anantakrroy** [comment]
So, the error was due to the use of `single quotes` in the npm script `"watch": "tsc-watch --onSuccess 'node ./dist/server.js' ",` . Solved the issue by escaping double quotes.

`"watch": "tsc-watch --onSuccess \"node ./dist/server.js\"",`
