### ISSUE TITLE
Request: debounce/delay option

### ISSUE THREAD

**Issue by Soumil07** [gilamran/tsc-watch#108]
When I save 2 files at once, ts-watch compiles and runs twice. An option like `--delay 2000` should debounce compiling by 2 seconds, so the 2 file changes are compiled only one time.

**Comment by gilamran** [comment]
The compilation and watch are done by typescript itself... If this is an issue, it's a typescript issue...

**Comment by Soumil07** [comment]
Got it. Merry Christmas!
