### ISSUE TITLE
Run onSuccess on pressing r

### ISSUE THREAD

**Issue by eguneys** [gilamran/tsc-watch#115]
I want to run onSuccess when nothing changes, by pressing r or something.

**Comment by gilamran** [comment]
Can you explain your reasons? usecase

**Comment by eguneys** [comment]
I write a typescript program for testing my website, when I update my website code, I want to run the program again.

**Comment by gilamran** [comment]
"a typescript program"?
Can you be more specific?

**Comment by eguneys** [comment]
I run `tsc-watch` on my typescript files, that compiles a program that tests my website on successful compilation. now sometimes I don't change my typescript files but change my website's code. now I want to run the tests again that is the same command I pass to `tsc-watch --onSuccess` flag , so In order to force a run, I superfluously change my tests code to trigger a recompilation and onSuccess to run, while I could simply press r and trigger onSuccess without recompilation.

**Comment by gilamran** [comment]
Just published `v4.4.0`.
I've implemented messages on `tsc-watch`, this ability opens up the `client` to external scripts with custom behaviors.

An example can be found [here](https://github.com/gilamran/tsc-watch/blob/master/tsc-watch-client-example.js)
