### ISSUE TITLE
TS5042: Option 'project' cannot be mixed with source files on a command line.

### ISSUE THREAD

**Issue by kirevdokimov** [gilamran/tsc-watch#118]
Getting this running `tsc-watch -p tsconfig.server.json --onSuccess 'npm run start'` or `tsc-watch --onSuccess 'npm run start' -p tsconfig.server.json` using `node v12.14.0` `npm v7.12.1` on `Microsoft Windows 10 Home 10.0.19042 N/A Build 19042`

**Comment by kirevdokimov** [comment]
Same commands works just fine from WSL1 `os: Debian, kernel: x86_64 Linux 4.4.0-19041-Microsoft`

**Comment by kirevdokimov** [comment]
Example to reproduce
[empl-118.zip](https://github.com/gilamran/tsc-watch/files/6462062/empl-118.zip)
```
> npm i
```
A-case (not my case, but new bug-like behaviour i got during research)
```
> npm run a

12:19:32 AM - Starting compilation in watch mode...

error TS6231: Could not resolve the path 'helloa'' with the extensions: '.ts', '.tsx', '.d.ts'.
  The file is in the program because:
    Root file specified for compilation
```
B-case with the problem from title
```
> npm run b

error TS5042: Option 'project' cannot be mixed with source files on a command line.
```

C-case same as A
```
> npm run c

12:21:11 AM - Starting compilation in watch mode...

error TS6231: Could not resolve the path 'helloc'' with the extensions: '.ts', '.tsx', '.d.ts'.
  The file is in the program because:
    Root file specified for compilation
```

D-case Works just fine
```
> npm run d
12:22:47 AM - Starting compilation in watch mode...

12:22:47 AM - Found 0 errors. Watching for file changes.

```

**Comment by kirevdokimov** [comment]
[This comment](https://github.com/nodejs/node-v0.x-archive/issues/25814#issuecomment-129523563) explain why it works as it works. It is possible to add merge step for single quoted arguments, but should we?

**Comment by gilamran** [comment]
I'm not sure, but isn't this a typescript issue and not tsc-watch?

**Comment by kirevdokimov** [comment]
> 
> 
> I'm not sure, but isn't this a typescript issue and not tsc-watch?

Judging by comment mentioned before, actually this is neither tsc-watch or typescript problem. Just misunderstanding point with windows shell rules :)
