### ISSUE TITLE
the root tsconfig.json isn't used.

### ISSUE THREAD

**Issue by jey07ro** [gilamran/tsc-watch#12]
I have all the sources in the `src` folder when I execute `tsc-watch` the root folder tsconfig.json isn't used.
Any suggestions?

**Comment by gilamran** [comment]
Is it working with `tsc`?

**Comment by gilamran** [comment]
Still waiting for an answer... 
As `tsc-watch` is using `tsc` to actually compile the code, I don't see any good reason for `tsconfig.json` issues...

**Comment by roblav96** [comment]
@gilamran This simply amazing repo works perfectly fine! Game changer :D

**Comment by gilamran** [comment]
Thanks @roblav96!

**Comment by gilamran** [comment]
As there's no response, I'm closing this issue.
