### ISSUE TITLE
Consider adding a hook for a command to run before each recompilation

### ISSUE THREAD

**Issue by axtk** [gilamran/tsc-watch#120]
would be nice to have a parameter for a command which would be run whenever a file change is detected but before the compilation begins

**Comment by gilamran** [comment]
Why would you need something like that?
can you give a real life example?

**Comment by axtk** [comment]
in my case, I want to get some timing info about the build process
with this hook, I would be able to set an initial timestamp

**Comment by gilamran** [comment]
There are much easier and more accurate options to do that...
Look into the `time` command

**Comment by axtk** [comment]
can't check it right now, but it seems like that will only give a single execution time of `tsc-watch` no matter how many times it recompiles, instead of producing a series of compilation times within a watch session (what I'm after)

**Comment by gilamran** [comment]
ok, cool
How about a PR?
add a `onCompilationStarted` flag?

**Comment by dko-slapdash** [comment]
@gilamran @axtk I submitted a PR for this feature: https://github.com/gilamran/tsc-watch/pull/122 - could you please take a look? (It includes changes in the arguments, in events emitted, in unit tests and also in README, i.e. I tried to make the new option appear in all the same places where onCompilationComplete is mentioned.)

**Comment by gilamran** [comment]
Great, I'll go over it later today!

**Comment by dko-slapdash** [comment]
Thanks @gilamran, waiting for your feedback and is ready to implement/apply any comments/suggestions.

**Comment by gilamran** [comment]
Thanks to @dko-slapdash this was solved in v4.5.0
