### ISSUE TITLE
Using `npx tsc-watch ...` in scripts fails to find tsconfig

### ISSUE THREAD

**Issue by nawlbergs** [gilamran/tsc-watch#125]
Suddenly this morning, Im having problems with tsc-watch while using npx to target nodes bin dir.  No idea why.. it worked Friday.. now (on monday) my server was not starting.  (i did restart windows).. so maybe windows updated something.... but heres what my team is using in package:
```
"wtf1": "    tsc-watch --noClear -p ./tsconfig.json --onSuccess \"cross-env NODE_ENV=local node ./dist/app.js\"", // works
"wtf2": "npx tsc-watch --noClear -p ./tsconfig.json --onSuccess \"cross-env NODE_ENV=local node ./dist/app.js\"", // error
"wtf3": "    tsc-watch --noClear --onSuccess \"cross-env NODE_ENV=local node ./dist/app.js\"", // works
"wtf4": "npx tsc-watch --noClear --onSuccess \"cross-env NODE_ENV=local node ./dist/app.js\"",  // error
```
results in:
```
wtf1: works
wtf2: error TS5042: Option 'project' cannot be mixed with source files on a command line.
wft3: works
wtf4: error TS6504: File 'dist/app.js' is a JavaScript file. Did you mean to enable the 'allowJs' option? ..
```

our original command we use in our project is `wtf4`

**Comment by gilamran** [comment]
Is this your `package.json` scripts?
Also, why are you using `npx` inside the `package.json`?

**Comment by nawlbergs** [comment]
Yes in package.json sorry.
I generally just use npx everywhere.  Its what are team just does.. it forces usage of the installed bin from package. (like.. instead of a global version or etc etc).
```
"runJustTsc": "npx tsc" // builds as expected.  
```
running any other command with npx inside package.json seems to work fine... and last week.. this worked for tsc-watch as well....  so im just  trying to figure out what changed.  :)    This has not effected our team (tho they are on macs and im the only one using a pc right now)

**Comment by gilamran** [comment]
It happens only on windows?

**Comment by gilamran** [comment]
Looks like there are several issues reported to npx: 
https://github.com/npm/npx/issues/10
https://github.com/npm/npx/issues/43
https://github.com/eslint/eslint/issues/13733
