### ISSUE TITLE
Runs `onSuccess` twice consecutively after a file save.

### ISSUE THREAD

**Issue by eguneys** [gilamran/tsc-watch#130]
When I save a file, it runs the tests and clears the screen and runs the tests again happens in 1 second. So it fires twice consecutively. It's annoying.

**Comment by gilamran** [comment]
Can you provide an example code to reproduce?

**Comment by eguneys** [comment]
Run `yarn watch`, make changes in `src/pos.ts` save.

`https://github.com/eguneys/muchess`

**Comment by gilamran** [comment]
I don't get see it running twice... only once
note that you can use `--noClear` flag to see the full output

**Comment by eguneys** [comment]
I think this is happening https://github.com/microsoft/TypeScript/issues/37994
I set --synchronousWatchDirectory and it works ok.

**Comment by gilamran** [comment]
@eguneys any updates on this one?
