### ISSUE TITLE
tsc-watch: command not found. 

### ISSUE THREAD

**Issue by jordanlesich** [gilamran/tsc-watch#133]
Hey, after following the instructions on the npm page, I can't get tsc-watch to even run. 

Odds are there's a missing step that I'm not doing, but if that's the case, it should be made clear from the docs. 

How to reproduce: 
- have a basic typescript project with a .tsconfig/dist folder etc. 
- save tsc-watch as dev dependency. ``npm install tsc-watch --save-dev``
- run tsc-watch command pointing to your app ex. ``tsc-watch --onSuccess "node ./dist/index.js"``

get this error back: 

``tsc-watch: command not found``

Obviously, there's something I'm not doing correctly. But I should be able to follow along with the docs and get the package set up.

**Comment by jordanlesich** [comment]
Worth noting that the package.json script instructions work.

**Comment by gilamran** [comment]
"Worth noting that the package.json script instructions work" what do you mean?

**Comment by gilamran** [comment]
I've updated the docs.
Let me know if this is clear enough.

Thanks.
