### ISSUE TITLE
doesn't seem to be running same compilation as "npx tsc -b -w"

### ISSUE THREAD

**Issue by craigphicks** [gilamran/tsc-watch#134]
`npx tsc-watch ` always succeeds, even when there should be an error, and nothing happens when target files are changed.

From the same directory, `npx tsc -b -w ` functions normally, detects errors and responds when they are fixed.

This is a hierarchical TS build with subdirectories - could that make a difference?  

(System Ubuntu 20, TS 4.4.4)

**Comment by gilamran** [comment]
I need a more detailed example to reproduce

**Comment by gilamran** [comment]
bump

**Comment by craigphicks** [comment]
@gilamran - Will get back to you!.  Please wait.

**Comment by craigphicks** [comment]
Sorry to have bothered you.  I will close this issue.
