### ISSUE TITLE
DX: Improve `tsc-watch` package

### ISSUE THREAD

**Issue by pp0rtal** [gilamran/tsc-watch#135]
Original issue

Steps:

- [ ] fork & use tsc-watch in the monorepo
- [ ] Improve library for us
  - [ ] improvement 1 / give ability to set `node` custom params
  - [ ] improvement 2 / detect node process failure SIGABRT
  - [ ] improvement 3 / create a new event `listed_file`
- [ ] Improve library for the world (official PR on https://github.com/gilamran/tsc-watch)
  - [ ] Sync improvement 1 
  - [ ] Sync improvement 2
  - [ ] Sync improvement 3
- [ ] Wait for `tsc-client` to be published on npmjs and reuse external package

**Comment by pp0rtal** [comment]
Sorry I'm planning to improve the lib for my company,
but this was some internal issue I was going too fast :man_facepalming: (improve for me, then propose my enhancements)

See you in a few weeks!

**Comment by gilamran** [comment]
I'd really appreciate it!
