### ISSUE TITLE
black on black text

### ISSUE THREAD

**Issue by bonjourjoel** [gilamran/tsc-watch#142]
Hi there,

Since a recent update, i have some text written black on black background in vscode. I believe some update was made to the "TSFILE:..." output's color. And it's not rendering well in vscode's default dark theme for example.
![bug-color-terminal](https://user-images.githubusercontent.com/78134277/161250162-5d514174-e7bb-48a4-8469-a95bd80dc640.png)

I have used the flag --noColor as a workaround... Maybe you could fix/reverse this?

Regards.

**Comment by gilamran** [comment]
@pp0rtal Looks like the coloring of the emitted files conflicts with vscode default dark theme... I want to revert the coloring of the file. any objection?

**Comment by pp0rtal** [comment]
@gilamran No objections, go ahead :+1: 

By the way and speaking of this, the feature works very well and I'm now able to post-process emitted files.
However, my console is flooded as sometimes hundred of files are rewritten depending the changes, and scrolling hides errors.
I'd like to introduce a specific `--hideListedEmittedFiles` to hide those occurrences.
I will open a dedicate ticket / PR for this to validate.

![Screenshot from 2022-03-29 10-37-26](https://user-images.githubusercontent.com/572334/161384899-44e15218-a918-411a-9491-d71dda071c4c.png)

**Comment by gilamran** [comment]
It's kinda conflicts with `--listEmittedFiles`, maybe have a new flag `--signalEmittedFiles`

**Comment by pp0rtal** [comment]
@gilamran I can take this update if you validate:
- `--listEmittedFiles` would pass this param to `tsc` and don't color it (and make `file_emitted` event work)
- `--signalEmittedFiles` would call `tsc` with `--listEmittedFiles` but fully hide `TSFILE:` lines (= modify tsc output)

Will do it on monday, I should base it on your v5 branch, right?

**Comment by gilamran** [comment]
@bonjourjoel Fixed on version 5.0.2

**Comment by bonjourjoel** [comment]
Great job, thanks!
