### ISSUE TITLE
Please tag published versions

### ISSUE THREAD

**Issue by coyoteecd** [gilamran/tsc-watch#146]
Version 5.0.2 lacks a tag, could you make sure in the future that code that gets published to npm is tagged accordingly?

**Comment by gilamran** [comment]
Pushed the missing tags.
Do you know of a suggested workflow that new version will be published and the tags will be pushed?

Thanks

**Comment by coyoteecd** [comment]
@gilamran I set up my repositories to publish via Travis, it's pretty simple to do. For the build config, you can find an example here: https://github.com/coyoteecd/serverless-s3-cleaner/blob/master/.travis.yml. This means you do `npm version minor/major` locally, which creates a tag automatically - you can configure the tag name/commit via [.npmrc](https://github.com/coyoteecd/serverless-s3-cleaner/blob/master/.npmrc). You then just push the tag to origin. The build then picks up the tag and publishes the package automatically (therefore you can't miss the tagging part).

If you don't like Travis, I'm sure you can find other alternative by looking at other projects here in github.
