### ISSUE TITLE
Support for TypeScript Project References  / --build mode 

### ISSUE THREAD

**Issue by bohdyone** [gilamran/tsc-watch#150]
Hi,

I'm looking at integrating your groovy tool into my monorepo, but it seems like it doesn't yet support `tsc --build --watch`?

This is useful to pick up and reload based on changes to dependencies as well as the project under test.

See here for more info:
https://www.typescriptlang.org/docs/handbook/project-references.html#tsc--b-commandline

Cheers.

**Comment by gilamran** [comment]
Can you share an example? or just put some example code here?

**Comment by bohdyone** [comment]
You can see an example of project references in action in the official TS repo: https://github.com/microsoft/TypeScript/blob/main/src/tsserver/tsconfig.json

In terms of the changes required in the watch step, it's pretty much just running `tsc --build --watch` instead of `tsc --watch`, at least in the simplest case.

**Comment by gilamran** [comment]
Why are you saying that it's not working?
can you share an example of the fail?

**Comment by bohdyone** [comment]
Perhaps I'm misunderstanding -- I thought that this package just ran `tsc
--watch` under the hood. Is there a way to specify `--build`?

**Comment by gilamran** [comment]
did you try to add `--build`?

**Comment by bohdyone** [comment]
I'm sorry, I completely misunderstood how `tsc-watch` works with regards to the handling of arguments. I see now that you simply parse additional arguments and then pass through the rest to `tsc`, so adding `--build` does indeed work. Quite a future-proof design.

Apologies for the needless issue!
