### ISSUE TITLE
Document how to use --incremental?

### ISSUE THREAD

**Issue by russell-dot-js** [gilamran/tsc-watch#155]
Using incremental builds with typescript is usually preferred to improve compilation time, especially in watch mode, but tsc-watch does not enable incremental builds by default. There is also no documentation on how to pass the `--incremental` flag to tsc

In fact, there is no documentation on this feature at all, but if you read through the code, any arguments that are not tsc-watch arguments will be passed through to tsc. For example, `tsc-watch --onSuccess="echo 'hello'" --incremental` will pass `--incremental` down to tsc

You should probably document this feature?

**Comment by gilamran** [comment]
well, as you mentioned `tsc-watch` is passing all the none tsc-watch parameters to `tsc` so, if `tsc` supports `--incremental` then `tsc-watch`.
What do you want me to document?

**Comment by russell-dot-js** [comment]
Exactly that. There is no documentation other than this issue than non tsc-watch params are forwarded to tsc

**Comment by gilamran** [comment]
How about a PR?

**Comment by gilamran** [comment]
Done
