### ISSUE TITLE
Wrong export of TscWatchClient in version 6.0.0

### ISSUE THREAD

**Issue by ibc** [gilamran/tsc-watch#156]
This code no longer works in 6.0.0:

```ts
const TscWatchClient = require('tsc-watch/client');

const client = new TscWatchClient();
```

It throws:

```
Uncaught TypeError: TscWatchClient is not a constructor
```

Why? Because `tsc-watch/client.ts` no longer exports the `TscWatchClient` class but an object with a `TscWatchClient` field. So the way to make it work in 6.0.0 is:

```ts
const { TscWatchClient } = require('tsc-watch/client');

const client = new TscWatchClient();
```

But not even the example in the README and src honours it:

- https://github.com/gilamran/tsc-watch#from-javascript
- https://github.com/gilamran/tsc-watch/blob/master/tsc-watch-client-example.js#L2

The test works because it imports it properly:

- https://github.com/gilamran/tsc-watch/blob/master/src/test/client.test.ts#L2

**Comment by ibc** [comment]
In v5.0.3 (before migrating TypeScript), `lib/client.ts` exports the class rather than an object containing the class: 

https://github.com/gilamran/tsc-watch/compare/v5.0.3...master#diff-ca407d959d33ce92a7f7efee354a5ea5e6e61fcd797d32c04205e429a074ed54L58

```js
module.exports = TscWatchClient;
```

But this changed in 6.0.0 in `src/client/client.ts`:

```ts
export class TscWatchClient extends EventEmitter {
```

Honestly I prefer the latter (it's a good practice to avoid `default` exports in ES6. However then the README and example code is wrong.

**Comment by ibc** [comment]
Kindly ping.

**Comment by gilamran** [comment]
Been very busy.
I'll get to it soon.
If you want to create a PR that would be great!

**Comment by ibc** [comment]
Don't worry 😊

In order to write a PR I need to know what is correct: docs or examples? Would you accept a PR that revers the behavior so "client" doesn't export an object but just the client itself?

**Comment by gilamran** [comment]
I think that we should go with the examples, wdyt?

**Comment by ibc** [comment]
Absolutely agreed. Will write PR.

**Comment by ibc** [comment]
I've changed my mind after trying to do it. `export default` is very discouraged in ES6 world:
- https://rajeshnaroth.medium.com/avoid-es6-default-exports-a24142978a7a
- https://blog.piotrnalepa.pl/2020/06/26/default-exports-vs-named-exports/
- https://www.reddit.com/r/javascript/comments/9amkc6/export_default_considered_harmful/

In fact while trying to do it I'm facing typical problems because there is some ugly trick to be done for `export default` to not export an Object with a `default` field into it and so on.

So I'll write a PR that just modifies the README and the example.

**Comment by ibc** [comment]
PR created: https://github.com/gilamran/tsc-watch/pull/158
