### ISSUE TITLE
On windows compiler path issue.

### ISSUE THREAD

**Issue by AdnanAliArshadtx** [gilamran/tsc-watch#159]
I have created a command in package.json using [tsc-watch](https://www.npmjs.com/package/tsc-watch) which is shown below:

`"npx tsc-watch --noClear --compiler ./node_modules/.bin/tsc --onSuccess 'node ./dist/src/index.js'"`

Also tried:

`"npx tsc-watch --noClear  --compiler ./node_modules/.bin/tsc --onSuccess \"node ./dist/src/index.js\""`

They work perfectly fine on mac but when I run it inside windows it throw below error:
```
\node_modules\.bin\tsc:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
```

Not sure if there is anything wrong with compiler path or anything I am missing.
Thanks in advance.

**Comment by gilamran** [comment]
if you installed `tsc-watch` you don't need to use `npx`.
Can you please try changing the command to: `tsc-watch --noClear  --compiler ./node_modules/.bin/tsc --onSuccess \"node ./dist/src/index.js\" `

**Comment by AdnanAliArshadtx** [comment]
I tried after installing the `tsc-watch` but still the same error.

**Comment by AdnanAliArshadtx** [comment]
Same result with the command `tsc-watch --noClear  --compiler \"./node_modules/.bin/tsc\" --onSuccess \"node ./dist/src/index.js\" `

I am specifying the compiler to ensure that it picks the right one.

**Comment by gilamran** [comment]
Try `tsc-watch --noClear --onSuccess \"node ./dist/src/index.js\"`

**Comment by AdnanAliArshadtx** [comment]
Yeah it worked even with npx but without --compiler.

`"npx tsc-watch --noClear --onSuccess \"node ./dist/src/index.js\""`
