### ISSUE TITLE
Feature request: Support multiple tsconfig.json files

### ISSUE THREAD

**Issue by jonaskello** [gilamran/tsc-watch#16]
My application is a monorepo with multiple packages where each package have it's own tsconfig.json. I would like to restart my server on a change to any of the packages. So for example I want to to this:

```
tsc-watch -p ./packages/foo-server -p ./packages/foo-utils --onSuccess 'node ./packages/foo-server/lib/server.js' -
```

So the request is to support multiple instances of the `-p`. The regular `tsc --watch` only supports one instance.

**Comment by jonaskello** [comment]
If `-p` would also support globbing it would even simpler to watch all packages in a monorepo:

```
tsc --watch -p ./packages/*/tsconfig.json
```

There is a related issue in the typescript repo [here](https://github.com/Microsoft/TypeScript/issues/17611);

**Comment by gilamran** [comment]
@jonaskello **tsc-watch** is using the **installed typescript** on your project, it is only forcing watch mode.
Once typescript will be able to use more than one `tsconfig.json` **tsc-watch** will support it too.

If you are using multiple `tsconfig.json` files, you are probably separating client from server.
I have another repo. that demonstrate just that: [fullstack-typescript](https://github.com/gilamran/fullstack-typescript)

![image](https://user-images.githubusercontent.com/1621965/35474954-9db8b806-039e-11e8-8291-121c80e6688a.png)

You can see how I managed 2 `tsconfig.json` files, including shared code.
If you change a client code, only the client code will be recompiled, and refreshed.
If you change the server code, only the server will be recompiled and restarted.
If you change the shared code, both will.

Hope this help.

**Comment by jonaskello** [comment]
@gilamran Yes, I understand how it works, I have read the source :-).

I previously also used an approach similar to your fullstack example. However lately I realised the advantages of yarn workspace so in my latest project I'm using a proper monorepo with multiple packages instead. See [here](https://github.com/Quramy/lerna-yarn-workspaces-example) for an example how that is setup. There are many advantages to have real packages for shared code instead of just separate folders under `./src`. In this case each package is compiled into it's own lib folder and with yarn workspace (or lerna) they can easily reference each other using regular `node_modules` resolution. You can also publish some of the packages to be used in other projects.

I think tsc-watch could actually support muliple `-p` quite easily, it is just a matter of spawning multiple tsc processes and then listening on output from all of them and restarting the server if any of them re-compiles. So the only code that would need to change is the one that spawns the tsc process. All listener code would be the same. I could make PR for this if you want to see how it would work.

**Comment by gilamran** [comment]
@jonaskello Thanks for the explanation.
As typescript itself is going forward with this feature, I don't want to do a double work on that.
Once they implement it, tsc-watch will have that automatically.
I would have considered this if they didn't plan on doing it...

**Comment by jonaskello** [comment]
If the typescript team will add this that would be really nice. But I'm not sure they will? Do you have a reference to an official statement on that? 

I've been following [this issue](https://github.com/Microsoft/TypeScript/issues/3469) which is referenced by the issue I mentioned previously. However they have been discussing since 2015 and I have not seen any concrete statements that they will do anything as of yet.

**Comment by jonaskello** [comment]
I went with a mix of webpack and nodemon for my monorepo. I guess multiple `-p` is not a perfect solution either because for the initial compilation a dependency order would have to be established and that is not so simple.
