### ISSUE TITLE
Best tool for the job

### ISSUE THREAD

**Issue by vitaly-t** [gilamran/tsc-watch#163]
I have tried many other solutions before this - `nodemon` with `ts-node`, `tsx`, etc, and found none of them to be usable, because they would not give us a proper TypeScript compilation error, which in my view makes them useless for this task.

Great job on this tool. It works like a charm, and produces TypeScript errors as expected.

I wonder though why no official releases within GitHub? :wink:

**Comment by gilamran** [comment]
Not really familiar with it, I'll investigate... do you have a suggestion?

**Comment by vitaly-t** [comment]
A suggestion on how to publish a release? 😄

**Comment by gilamran** [comment]
I meant a place to learn/investigate... but found one.

**Comment by gilamran** [comment]
Done

**Comment by vitaly-t** [comment]
Nice, thank you!!!
