### ISSUE TITLE
Add `--onEachCompilationStarted` option

### ISSUE THREAD

**Issue by zanminkian** [gilamran/tsc-watch#169]
I want to run `rm -rf dist` before each compilation. `--onCompilationStarted` seems only work at the beginning (initial), not each compilation.

`--onCompilationComplete` will work **after** every compilation, so we need an option to work **before** every compilation. I think it make sense.

**Comment by gilamran** [comment]
The watch option is implemented by typescript itself, and not tsc-watch. That's why I can not hook into the "before" compilation...
