### ISSUE TITLE
--noClear doesn't work

### ISSUE THREAD

**Issue by staszekj** [gilamran/tsc-watch#172]
## Current behaviour
➜  `echo "This text should not be removed"`
This text should not be removed
➜  `npm list tsc-watch --depth=0`
|--tsc-watch@6.2.0
➜  `npx tsc -v`
Version 4.6.3
➜  `npx tsc-watch --noClear`

**Console is clear here and only the lines below stay there**

6:39:34 PM - Starting compilation in watch mode...
6:39:36 PM - Found 0 errors. Watching for file changes.

## Expected behaviour
➜  `echo "This text should not be removed"`
This text should not be removed
➜  `npm list tsc-watch --depth=0`
|--tsc-watch@6.2.0
➜  `npx tsc -v`
Version 4.6.3
➜  `npx tsc-watch --noClear`
6:39:34 PM - Starting compilation in watch mode...
6:39:36 PM - Found 0 errors. Watching for file changes.

**Comment by gilamran** [comment]
Fixed in version 6.2.1.
Thanks
