### ISSUE TITLE
does this ignores my tsconfig.json file?

### ISSUE THREAD

**Issue by johhansantana** [gilamran/tsc-watch#24]
Not sure but when I use regular `tsc` compare to `tsc-watch` it compiles differently.

Also I have these:
```
"noUnusedLocals": true,
"noUnusedParameters": true
```

When I run regular `tsc` it fails if it meets these rules but with `tsc-watch` it succeeds even with these rules which makes me assume that it's ignoring the `tsconfig.json` file

**Comment by gilamran** [comment]
Bump.

**Comment by justvamp** [comment]
Shows errors where ```tsc -w``` doesn't.

**Comment by gilamran** [comment]
Can anyone approve of this issue?

**Comment by johhansantana** [comment]
It seems like it's working now somehow. I'm not really sure if it was on my end but after running:
```
ts-watch --onSuccess 'node ./server.js'
```
it does use my config.

Sorry for the issue.

**Comment by jonaskello** [comment]
I bumped into the same problem. However it was a config issue. Following the readme I did:

```
    "start": "tsc-watch server.ts --onSuccess \"node ./lib/server.js\" --onFailure \"echo Beep! Compilation Failed\"",
```

But I should not have specified the file `server.ts`. I think if you specify the file, tsc will not think of it as a project and thus not use tsconfig.json. So what I wanted was this:

```
    "start": "tsc-watch --onSuccess \"node ./lib/server.js\" --onFailure \"echo Beep! Compilation Failed\"",
```

Just removed the filename and it started to work :-).

**Comment by DutchKevv** [comment]
can this please be noted in the README?? It took me half a day to figure out why my tsconfig.json wasn't used :)

> I bumped into the same problem. However it was a config issue. Following the readme I did:
> 
> ```
>     "start": "tsc-watch server.ts --onSuccess \"node ./lib/server.js\" --onFailure \"echo Beep! Compilation Failed\"",
> ```
> But I should not have specified the file `server.ts`. I think if you specify the file, tsc will not think of it as a project and thus not use tsconfig.json. So what I wanted was this:
> 
> ```
>     "start": "tsc-watch --onSuccess \"node ./lib/server.js\" --onFailure \"echo Beep! Compilation Failed\"",
> ```
> Just removed the filename and it started to work :-).

**Comment by gilamran** [comment]
Cool, thanks.
README updated
