### ISSUE TITLE
v1.0.19 Needs a revert :X

### ISSUE THREAD

**Issue by roblav96** [gilamran/tsc-watch#26]
Since upgrading from `v1.0.18` to `v1.0.19` I've noticed two things.

1. The `--onSuccess` hook never gets called when a compilation error occurs. Maybe look up the `noEmitOnError` field in the project's `tsconfig.json`.
2. You're toying with my console by modifying colors and such. lol I've been using this for so long now, that change is something I'm not used to and my reflexes immediately make me think there's an error. Kinda goes nicely with my [tsc-wtf](https://github.com/roblav96/tsc-wtf) project.

Hope you're OK with hearing constructive criticism. I absolutely love the work you've done on this project and I use it every single day. Cheers mate! :D

**Comment by gilamran** [comment]
Thanks for the information!
I'll need more information/example/screenshots on your issues to understand what's going on.
Waiting for your response.

**Comment by gilamran** [comment]
I just noticed that typescript 2.8 added `--preserveWatchOutput` to do just that.
I'm removing the `noClearScreen`

**Comment by roblav96** [comment]
@gilamran Just a heads up, `tsc-wtf` gets applied to your global install of typescript if it exists :X Great work!

**Comment by gilamran** [comment]
So, can I close this issue? are we ok, or do we have an issue?
