### ISSUE TITLE
Incorrect version of tsc used

### ISSUE THREAD

**Issue by jonaskello** [gilamran/tsc-watch#28]
I upgraded a project to typescript 2.9.1 and  encountered a strange behavior. It seems tsc-watch is still using typescript 2.8.3 but I don't understand where it finds it. This is on Windows 10.

Some output:

```
$ tsc-watch --version
Version 2.6.2

$ tsc --version
Version 2.9.1

$ yarn tsc-watch --version
yarn run v1.7.0
$ C:\code\XXX\node_modules\.bin\tsc-watch --version
Version 2.8.3

$ yarn tsc --version
yarn run v1.7.0
$ C:\code\XXX\node_modules\.bin\tsc --version
Version 2.9.1

$ which tsc
/c/Users/jonkel.DIVID/AppData/Roaming/npm/tsc

$ /c/Users/jonkel.DIVID/AppData/Roaming/npm/tsc --version
Version 2.9.1

$ yarn which tsc
yarn run v1.7.0
$ C:\code\XXX\node_modules\.bin\which tsc
C:\code\XXX\node_modules\.bin\tsc.CMD
```

I'm trying to find out where `tsc-watch` is finding the old `tsc` binary. It seems it is not looking at the global path or at the path yarn sets.

**Comment by gilamran** [comment]
[This](https://github.com/gilamran/tsc-watch/blob/master/lib/tsc-watch.js#L120) is how tsc is being resolved:
```
const bin = require.resolve('typescript/bin/tsc');
```
Is there a better approach?

**Comment by jonaskello** [comment]
Not sure, I will do some research. Meanwhile I found out that I had an old version of `tsc-watch` globally installed (I think it was 1.0.15 or something). When I upgraded to 1.0.22 the global now resolves to the correct `tsc` but the local one in my project still somehow finds an old `tsc`. This is what I have now with 1.0.22 both global and local:

```
$ tsc --version
Version 2.9.1
$ tsc-watch --version
Version 2.9.1

$ yarn tsc --version
Version 2.9.1
$ yarn tsc-watch --version
Version 2.8.3
```

**Comment by jonaskello** [comment]
I found out what causes this. Somehow the `tsc-watch` package got it's private version of the `typescript` package in my project. So the directory structure is like this:

```
myproj
- node_modules
-- typescript (this is 2.9.1)
-- tsc-watch
--- node_modules
---- typescript (this is 2.8.3)
```

Not sure why this is happening, probably something `yarn` does when it installs for some reason. I can see that the `package.json` in `tsc-watch` has `"typescript": "*"` which seems correct to me.

My yarn.lock is probably the culprit here as it looks like this:

```
typescript@*:
  version "2.8.3"
  resolved "https://registry.yarnpkg.com/typescript/-/typescript-2.8.3.tgz#5d817f9b6f31bb871835f4edf0089f21abe6c170"

typescript@^2.4.2, typescript@^2.6.1:
  version "2.8.1"
  resolved "https://registry.yarnpkg.com/typescript/-/typescript-2.8.1.tgz#6160e4f8f195d5ba81d4876f9c0cc1fbc0820624"

typescript@^2.9.1:
  version "2.9.1"
  resolved "https://registry.yarnpkg.com/typescript/-/typescript-2.9.1.tgz#fdb19d2c67a15d11995fd15640e373e09ab09961"
```

I'll have to investigate further why this is. Anyway this seems to be unrelated to `tsc-watch` itself, sorry for the confusion. And thanks for releasing 1.0.22 with typescript 2.9 support, keep up the good work :-).

**Comment by gilamran** [comment]
ok, keep me posted on your investigation.

Thanks!

**Comment by jmoseley** [comment]
I discovered that moving `tsc-watch` from a dev dependency to a regular dependency may have resolved this.

**Comment by jmoseley** [comment]
Though that may be incorrect. A correct fix may be to move `typescript` into `peerDependencies`?

**Comment by jonaskello** [comment]
I resolved it by deleting the entries in yarn.lock and rerunning yarn. Then I got a single entry. Not sure why yarn did this but now that yarn.lock has a single typescript entry it works.
