### ISSUE TITLE
Incorrect quote handling

### ISSUE THREAD

**Issue by mscharley** [gilamran/tsc-watch#35]
The following doesn't work properly:

```
tsc-watch --onSuccess 'concurrently -n http,queue "node dist/server.js" "node dist/queue.ts"'
```

At a guess, this looks like the culprit: https://github.com/gilamran/tsc-watch/blob/master/lib/tsc-watch.js#L71

I'm not sure why this is being done in the first place to know how to approach fixing it though.

**Comment by gilamran** [comment]
Cool, thanks for the nice catch.
Fixed on version 1.0.28
