### ISSUE TITLE
1.0.27 -> 1.0.28 regression

### ISSUE THREAD

**Issue by onehorsetown** [gilamran/tsc-watch#36]
Looks like something broke in 1.0.28.  

Look at:

https://github.com/gilamran/tsc-watch/blob/ae2f5a8050ce0a166a1a934555216087e149d81b/lib/tsc-watch.js#L71-L78

I think you either want:

```
    const args = parts.splice(0, 1);
    return spawn(exec, parts, {
```

or

```
    const args = parts.slice(1);
    return spawn(exec, args, {
```

**Comment by gilamran** [comment]
Thanks, fixed on version 1.0.29
