### ISSUE TITLE
Custom compiler support

### ISSUE THREAD

**Issue by sla100** [gilamran/tsc-watch#38]
The tsc-watch i awesome but has a hard-written compiler name:
File lib/tsc-watch.js Line 129: 
`const bin = require.resolve('typescript/bin/tsc');`

but there are other compilers compatible with typescript for example ntypescript, ttypescript.

Webpack plugin - awesome-typescript-loader allows you to choose a compiler by an optional parameter:
`--compiler (string) (default='typescript')`

Could you have parameterized tsc-watch in a similar way?

**Comment by gilamran** [comment]
Sounds good to me, how about a PR?

**Comment by gilamran** [comment]
Resolved on v1.0.30 - 10/10/2018
