### ISSUE TITLE
run without --watch

### ISSUE THREAD

**Issue by matheusdavidson** [gilamran/tsc-watch#4]
Hi there, i`m using this plugin to get the success callback and start my node server after the compiler is done. For dev its ok, because i need the --watch flag, but for building purposes, i don`t need to watch, just need the success callback, would be great to have the option to disable --watch, do you plan to do that?

**Comment by gilamran** [comment]
`tsc-watch` is intended for dev time only, for build you should use the regular `tsc`

**Comment by mpicard** [comment]
haha
