### ISSUE TITLE
tsconfig.json path

### ISSUE THREAD

**Issue by TGMorais** [gilamran/tsc-watch#41]
Hello,

Firstly, thanks for writing this package, it's been super useful!
I have a question, as it seems it's not been asked before, and I could not find anything about it in the docs:

Is it possible to set the path of the `tsconfig.json` ? For my build process needs I have to use a specific `tsconfig.build.json` and I was looking at how to use ts-watch with this file instead of the default.

I see there is compiler option, but no option to set a custom tsconfig file. (`-p` flag to it)
Would this be feasible ?

Cheers!

**Comment by gilamran** [comment]
`tsc-watch` is using the original (installed) `tsc`. meaning that it will still have all the original command-line options.
You should use the `-p PATH_TO_TSCONFIG` to specify custom tsconfig.json location.
If you still have issues with that, please provide a reproducible example.
If not, please close this issue.

Thanks
Gil Amran

**Comment by TGMorais** [comment]
Yes, you are correct!  
Silly me, I could have just tried that.

Doing like so, works just fine:
`tsc-watch --onSuccess \"npm run start\" -p tsconfig.build.json`  


Thank you.
