### ISSUE TITLE
Upgrade `ps-tree` dependency due to npm dependency attack

### ISSUE THREAD

**Issue by jeremyhon** [gilamran/tsc-watch#42]
https://github.com/dominictarr/event-stream/issues/116

An attacker gained control of the `event-stream` repository and injected malicious code. This package must be upgraded to the latest version of `ps-tree` to remove the malicious code. 

The latest version of this package installs `flatmap-stream` thanks to this dependency chain `ps-tree 1.1.0 > event-stream 3.3.6 > flatmap-stream 0.1.1`. 

This attack was a targetted attack at anyone who was using the `copay-dash` package, and would attempt to steal your BTC or BCH wallet keys.

**Comment by gilamran** [comment]
Thanks for the info!
Fixed on 1.0.31
