### ISSUE TITLE
Watch additional files.

### ISSUE THREAD

**Issue by nl-brett-stime** [gilamran/tsc-watch#44]
It'd be great to be able to specify additional files, outside of those included by `tsc` that are watched by this process.

E.g., if I make changes to a `.graphql` file somewhere in my directory tree, I'd like to have the watch process restart node without having `tsc` try to compile the file.

I have a feeling this will require integrating the better part of nodemon in order to get queued file system events across OS platforms. Sorry, no pull request today. Just recording the feature request for now.

**Comment by gilamran** [comment]
The "watch" ability that tsc-watch is using comes from typescript itself. Adding more watch capabilities is way out of scope for this project.
