### ISSUE TITLE
On Windows, running tsc-watch uses 50%-60% of CPU

### ISSUE THREAD

**Issue by kvgphl** [gilamran/tsc-watch#46]
When running tsc-watch, on my Windows machine, the CPU usage for the Node.js process alone spikes to 50%-60%.  With the other apps that I have running on my laptop, it basically spikes the total CPU usage to 100%.

This is how tsc-watch is being invoked:

`./node_modules/.bin/tsc-watch --onSuccess node build/server.js`

Is it correct to assume that the constant checking for file changes is what is causing the CPU usage spike?

Is there a polling option to configure how often tsc-watch checks for changes, or other way to resolve this issue?

Thanks!

**Comment by kvgphl** [comment]
Thanks for the suggestion.  I tried #1 and the CPU still spiked.  #2 (just the `tsc -w` part alone) caused the CPU to also spike.  It appears to be `tsc -w`.

This page about 'Configuring Watch`:
https://www.typescriptlang.org/docs/handbook/configuring-watch.html

describe the default option as follows:
"If environment variable TSC_NONPOLLING_WATCHER is set to true, watches parent directory of files (just like UseFsEventsOnParentDirectory). Otherwise watch files using fs.watchFile with 250ms as the timeout for any file"

The bottom of that page also says:
"`fs.watchFile` uses polling and thus involves CPU cycles. But this is the most reliable mechanism to get the update on the status of file/directory. Compiler typically uses `fs.watchFile` to watch source files, config files and missing files (missing file references) that means the CPU usage depends on number of files in the program."

This page says that `chokidar` has addressed this issue:
https://www.npmjs.com/package/chokidar

but want to exhaust all options with `tsc-watch` before trying another package.

Any other suggestions that I can try?

Thanks again for your help!

**Comment by gilamran** [comment]
@kvgphl well, great investigation!
But I don't see how to solve this, `tsc-watch` is using the TypeScript's internal watch...
And I don't see how we can fix this...

**Comment by imcotton** [comment]
I've just tried set `TSC_NONPOLLING_WATCHER=true`, and it works great on Mac OS, maybe have a flag for that in tsc-watch?

**Comment by lebesnec** [comment]
`TSC_NONPOLLING_WATCHER=true` solve my cpu usage problem on windows as well.
You can set in directly in your command in your `package.json`:

```
"scripts": {
    "watch": "set TSC_NONPOLLING_WATCHER=true && node_modules/.bin/tsc-watch --onSuccess \"node ./build/app.js\""
}
```
