### ISSUE TITLE
Formatting of terminal output is not ideal

### ISSUE THREAD

**Issue by thomas-darling** [gilamran/tsc-watch#48]
A few minor issues with the formatting of the terminal output :-)

After initial build:
* Only the `[` is colored. It would be better to color the whole line, except for the gray timestamp.

![image](https://user-images.githubusercontent.com/6388663/52435181-7a6e5400-2b11-11e9-90cb-4bf2ea794a4c.png)

After rebuilding:
* Two line breaks and a separator line is added. This might make sense when history is preserved, but when it clears the console before each build, it just seems weird and noisy.
* Again, only the `[` is colored.
* A single line break before and after the errors would improve readability.

![image](https://user-images.githubusercontent.com/6388663/52435245-a4c01180-2b11-11e9-99c9-30c95bb81001.png)

I'm on macOS by the way.

**Comment by gilamran** [comment]
Cool, thanks for the issue.
fixed on 1.1.37
