### ISSUE TITLE
tsc-watch kills the spawned process on recompilation

### ISSUE THREAD

**Issue by pronebird** [gilamran/tsc-watch#50]
Hi,

I run tsc-watch with the following command:

```
tsc-watch --sourceMap --onFirstSuccess "node run-my-app-that-does-hot-reload.js"
```

Changing any file kills the node process. How do you circumvent this?

*Workaround: Used a programmatic API via `tsc-watch/client` to prevent the node process from being killed*

**Comment by gilamran** [comment]
@pronebird, yeap, using the `tsc-watch/client` is the way to go.
I though about adding `--onFirstSuccessRunOnce` but that, just did not "sound good"...
If you have any other idea, please share. If not, and you're happy with your solution, please close this issue.

Thanks
Gil Amran

**Comment by pronebird** [comment]
`--onFirstSuccess` is supposed to execute only once so I believe that killing the process spawned by this hook is not necessary, not until about to quit the `tsc-watch` itself at least. Any particular reason why you do that?

**Comment by gilamran** [comment]
Well, this is not the first issue about the same thing... people do ask for this again and again.
BUT, this is a breaking change... so maybe the proper thing to do is to, bump the main version to 2. and fix that...
WDYT?

**Comment by pronebird** [comment]
Yeah, I'd say all breaking changes deserve a major bump. 

The best would be to rename the flag or deprecate it in favor of another flag, but I can't come up with a better candidate than `--onFirstSuccess`.

Btw, it got me thinking that the reason why you've designed `tsc-watch` this way was to prevent a bunch of scripts running simultaneously. So killing the process and starting the next one was a reasonable decision. But I think that `--onFirstSuccess` shouldn't follow that design, because it's meant to run only once, it makes no sense to run the same script from both `--onFirstSuccess` and `--onSuccess` handlers.

**Comment by gilamran** [comment]
Agreed, I'll publish a major version with this change soon.

**Comment by gilamran** [comment]
Version 2.0.0 just published, please give it a try and let me know of any issues ASAP.

Thanks again!

**Comment by pronebird** [comment]
Wow, so fast. 😮 I've just tested the new behaviour of the `--onFirstSuccess` option and it works as I had expected it to work in the first place. Thanks for working with me on this. 👍 I hope it saves hours of frustration to the others.
