### ISSUE TITLE
Please export a tsc-watch/client class

### ISSUE THREAD

**Issue by pronebird** [gilamran/tsc-watch#51]
Hi,

Currently `tsc-watch/client` exports a singleton. It makes it impossible to run multiple tsc-watch side by side. This is especially critical in the workspace configuration. Would it be possible to export the class itself instead of an instance?

**Comment by gilamran** [comment]
Can you please explain your situation? maybe with a given example?
And, why can't you just run `tsc-watch` several times?
Please remember that `tsc-watch` is reading the arguments, how would this work with several instances of `tsc-watch`?

**Comment by pronebird** [comment]
Mono-repo, two packages A and B. Running the app (project A) that depends on project B. 

When project B has changed, project A has to reload. I do soft reload when changing any frontend React stuff via BrowserSync and a hard reload when changing the main Electron process files which requires killing the process and restarting it.

```js
function startBrowserSync() {
  // start browser-sync and file watch
}

function prepareWatchArguments(projectPath) {
  return ['--noClear', '--project', projectPath];
}

const WatchClient = watch.constructor;
const appWatcher = new WatchClient();
const componentsWatcher = new WatchClient();

const appCompiledPromise = new Promise((resolve) => {
  appWatcher.on('first_success', () => {
    resolve();
  })
});

const componentsCompiledPromise = new Promise((resolve) => {
  componentsWatcher.on('first_success', () => {
    resolve();
  });
})

Promise.all([appCompiledPromise, componentsCompiledPromise])
  .then(() => {
    console.log('Take off..');
    startBrowserSync();
  });

appWatcher.start(...prepareWatchArguments(path.resolve(__dirname, '..')));
componentsWatcher.start(...prepareWatchArguments(path.resolve(__dirname, '../../components')));
```

**Comment by gilamran** [comment]
I see, looking good!
How about a PR? (Please add tests)
