### ISSUE TITLE
[Typescript version 2.7.2] onSuccess and onFailure callbacks do not seem to work

### ISSUE THREAD

**Issue by boyanio** [gilamran/tsc-watch#59]
In my `package.json` I have the following script defined:
```
"scripts": {
  "build": "cd someSubFolder && tsc-watch --onSuccess \"echo Success\" --onFailure \"echo Failure\""
}
```
When I run `npm run build` the TypeScript compilation seems to work along with the watch mode, however none of the two callbacks gets fired. What am I missing?

I am using typescript 2.7.2 and tsc-watch 2.2.1

**Comment by boyanio** [comment]
It seems this [commit](https://github.com/gilamran/tsc-watch/commit/225562f7b940e301677b95b3312558bfb9febe2d) has changed the regex, which causes the output from the TypeScript compiler not be recognized

**Comment by gilamran** [comment]
@boyanio thanks for the issue.
Typescript version 2.7.2 is a year and a half old... I (wrongly) assumed that people moved on.
A PR would be great.

Thanks
