### ISSUE TITLE
onSuccess does not seem to handle two commands accordingly

### ISSUE THREAD

**Issue by stringbeans** [gilamran/tsc-watch#60]
I have yarn commands like so...

```
    "copy-dangling": "copyfiles -u 1 src/**/*.json src/**/*.pug src/**/*.sql dist/",
    "dev": "yarn clean-dist && tsc-watch --onSuccess \"yarn copy-dangling && node --require dotenv/config dist/index.js\"",
```

because the onSuccess is running multiple commands, it seems to incorrectly parse out the ampersands `&&` and turns it into something like this:

`copyfiles -u 1 src/**/*.json src/**/*.pug src/**/*.sql dist/ '&&' node --require dotenv/config dist/index.js`

(notice the quotes around the ampersands)

**Comment by gilamran** [comment]
@stringbeans, what is the expected behavior?
How about creating a script that does everything that you need onSuccess and just call it?

**Comment by stringbeans** [comment]
@gilamran yes, i created a script that does everything and called it from onSuccess to get around this issue

the expected behaviour with the command `tsc-watch --onSuccess "yarn copy-dangling && node --require dotenv/config dist/index.js"` is that once the compilation is done it will run `yarn copy-dangling` and then `node -require dotenv/config dist/index.js`

**Comment by gilamran** [comment]
Yea, I see the problem.
But because `tsc-watch` is spawning the process (So it can kill it properly) it can't handle multiple tasks... I guess that the only solution would be to have a script for that.

**Comment by stringbeans** [comment]
@gilamran ahh makes sense. i see two possible actions here (let me know what you think):

A) modify the script to allow for multiple "onSuccess" flags (thus allowing multiple commands to be executed after success)

B) modify the README to mention this use case to others

cheers!

**Comment by gilamran** [comment]
Agreed, I'll mention it in the README.

**Comment by gilamran** [comment]
Fixed, thanks!

**Comment by chris-schmitz** [comment]
@stringbeans you're probably already past this considering it's years old, but another option is npm script composition. Here's an example from the project I'm working on:

```
  "scripts": {
    "start": "tsc && node dist/index.js",

    "dev": "tsc-watch --onSuccess 'npm run sync&host'",
    "sync&host": "npm run rsync:public && npm run host",
    "host": "npx kill-port 3000 && node ./dist/server/index.js",
    "rsync:public": "rsync -avzhP --exclude '*.ts' src/public/* dist/public"
  }
```

I wanted to sync the non-typescript  `src/public` folder over to my `dist/public` folder and restart the local node process. Rather than writing a node script to orchestrate multiple `child_process.exec` calls I just created an npm script `sync&host` to orchestrate the rest of the npm scripts. 

Set up this way you should be able to fire multiple services onSuccess.

**Comment by rhyek** [comment]
This another alternative:
```json
{
  "scripts": {
    "dev": "tsc-watch --onSuccess \"sh -c 'echo lol && node --inspect dist/main'\""
  }
}
```
