### ISSUE TITLE
Release tagging

### ISSUE THREAD

**Issue by notpeter** [gilamran/tsc-watch#61]
Hi!

I was wondering if it would be possible to tag releases?  I wanted to peek at a diff between two old versions was bummed to see only [a single tagged release](https://github.com/gilamran/tsc-watch/releases).

Future versions were tagged that would be helpful going forward, but I think it might not be too difficult to tag old releases assuming your [changelog commits are accurate](https://github.com/gilamran/tsc-watch/commits/master/CHANGELOG.md).

Since I can't propose tags via the PR process, a contributor would have to check out each of the dozen version refs from the changelog and run `git tag 1.x.x` and then push tags. It's PITA but it's 5mins for much better transparency.

Thanks in advance!

**Comment by gilamran** [comment]
Done, thanks!
