### ISSUE TITLE
Should resolve tsconfig paths for node

### ISSUE THREAD

**Issue by Astray-git** [gilamran/tsc-watch#62]
Is it possible to use [tsconfig-paths](https://github.com/dividab/tsconfig-paths) with tsc-watch?

**Comment by gilamran** [comment]
@Astray-git I'm not familiar with this library...
Did you try? I don't see any reason for it not to work...

**Comment by Astray-git** [comment]
Thanks. I end up put `npm run dev` in onSuccess command, then I can run `tsconfig-paths/register` as before
