### ISSUE TITLE
lib/stdout-manipulator.js

### ISSUE THREAD

**Issue by erikdeboer467** [gilamran/tsc-watch#72]
In windows there are to many empty line in the console output. This can be fixed by replacing the manipulate function in stdout-manipulator.js to this:

function manipulate(buffer) {
  const lines = buffer
    .toString()
    .split(/\r\n|\n|\r/gm)
    .filter(a => a.length > 0)
    .map(a => a.replace(tscUsageSyntaxRegex, newAdditionToSyntax));

  return lines;
}

output before:
------------------------------------------------------------------------------------
Web Server is running
09:37:14 - Starting compilation in watch mode...

09:37:15 - Found 0 errors. Watching for file changes.
Running webpack...
Webpack done!

output after changing the code:
------------------------------------------------------------------------------------
Web Server is running
09:44:17 - Starting compilation in watch mode...
09:44:18 - Found 0 errors. Watching for file changes.
Running webpack...
Webpack done!

Hoop you can change that in a future release.

**Comment by gilamran** [comment]
@erikdeboer467 cool, a PR would be great.

**Comment by gilamran** [comment]
@erikdeboer467 I've refactored the code to use readline instead of manipulating the raw stdout buffer. This was done on version 4.2.0 can you please take a look, and let me know if this also solves your issue?

Thanks
