### ISSUE TITLE
Send signal on reload

### ISSUE THREAD

**Issue by sla100** [gilamran/tsc-watch#73]
Is there way to send signal into process when code has been updatet? Something like:
```sh
tsc-watch --onFirstSuccess "node ./dist/main.js" --onSuccess SIGINT
```

**Comment by gilamran** [comment]
Actually we are sending the `SIGINT` to the process that was started in order to kill it...

**Comment by gilamran** [comment]
Does this solves your issue?

**Comment by sla100** [comment]
Yes, I will try to create PR in the future
