### ISSUE TITLE
after Starting compilation in watch mode. it exits no error

### ISSUE THREAD

**Issue by Dj-jom2x** [gilamran/tsc-watch#74]
after Starting compilation in watch mode. it exits xD

**Comment by gilamran** [comment]
Can you please give an example?

**Comment by Dj-jom2x** [comment]
it's fine now xD I don't really know what happened .. I revert to 3.7.x now... I always install @next version in the past... both dev and global... that's very odd scenario .. to do watch mode ... it seems it's watching something then just exit without saying anything
