### ISSUE TITLE
noClear not always working

### ISSUE THREAD

**Issue by Christilut** [gilamran/tsc-watch#78]
I'm running tsc-watch like this: `tsc-watch --noClear --onSuccess \"node --inspect dist/server/index.js\"`

Can't quite reproduce it reliable but what I'm observing is that after starting it, it works as expected a few times (doesn't clear terminal) but then when it reaches the bottom of the terminal, it starts clearing the screen. And from that point it clears the screen every time.

I'm using Git Bash (in ConEmu), Windows 10.

**Comment by gilamran** [comment]
I saw this also, and I think that it happened on the newer version of typescript.
Can you try to reproduce it with more details? I'll try to figure it out as well.

**Comment by Christilut** [comment]
I'm getting it as well when I scroll up a lot (few pages) and then trigger the reload. Then my entire terminal is blank. Then I press Enter so it's back at the normal position.

**Comment by gilamran** [comment]
Sorry, I'm having hard time reproducing this... Maybe you can give a better example?

**Comment by Christilut** [comment]
I can't really reliably reproduce it either... just seems to happen sometimes. Maybe it's specific to my emulator

**Comment by Janpot** [comment]
Seeing this as well, also without a reliable reproduction. Doing a quick review of your code and I notice that [in this check](https://github.com/gilamran/tsc-watch/blob/35f011d6842ef594fdaf8902d65d2272a92678e7/lib/tsc-watch.js#L50) it is assumed that a specific chunk of `[0x1b, 0x63]` will come in. I think this is a false assumption. If I understand these streams correctly, that sequence may come in as part of a larger chunk, or it might even be splitted over two separate chunks. I'm not sure, but this might be solvable by using the [`readline`](https://nodejs.org/api/readline.html) module to split this stdout into separate lines first.

**Comment by gilamran** [comment]
@Janpot great idea!
I've converted the current code work with readline instead of buffer.
As this is a fragile change, I've created an RC version. please use it on your projects to see that we're not breaking anything.

`npm install -D tsc-watch@next`

Thanks!

**Comment by Janpot** [comment]
Been using all day so far with `--noClear`, seems to be working fine for me.

**Comment by Janpot** [comment]
Also, not sure if you've explored this, but [using the typescript API directly](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API#writing-an-incremental-program-watcher) _could_ be a more reliable way to hook into the watch cycle.

**Comment by gilamran** [comment]
Published version 4.2.0 with the fix. thanks guys!
@Janpot I've created issue #80 to discuss your proposition.
