### ISSUE TITLE
Refactor the code to use typescript language services

### ISSUE THREAD

**Issue by gilamran** [gilamran/tsc-watch#80]
I was thinking about converting the code to use the [typescript language services](https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API#incremental-build-support-using-the-language-services) this for a long time.

**I'm not 100% sure about this.**
I afraid that this would over complicate the code, and will cause the library to be dependent on the version of TypeScript and api changes. The library will have to manage builds instead of just do action on compilation complete.

I know, reading the stdout is hack-ish, but it does the job and it's very small and simple. I've never used the api, and I might be very wrong here...

Before I go on and start working on it, what you do think about it?

**Comment by Janpot** [comment]
To be clear, I proposed this approach mainly because I'm interested in it from a technical point of view and I'm also interested in the benefits vs. the tradeoffs. I don't take the stance that it would be a better solution.
Which functionalities would implementing it this way unlock?

**Comment by gilamran** [comment]
For now, I'll leave this issue open

**Comment by elvizcacho** [comment]
@gilamran I think this is the right way to go. Depending on the stdout to check if the compilation was succesfull is error prone + you have to stick to a one typescript version. 
I would suggest to remove typescript as a dependency of the project and let the users choose the typescript version they want. 

A similar solution to the problem using the typescript language service would be as shown below:

``` javascript
// ts-watcher.js
const ts = require('typescript');
const { spawn } = require('child_process');

function getCommand() {
  const onSuccessIndex = process.argv.findIndex((arg) => arg === '--onSuccess');
  return process.argv.slice(onSuccessIndex + 1).join(' ');
}

const formatHost = {
  getCanonicalFileName: (path) => path,
  getCurrentDirectory: ts.sys.getCurrentDirectory,
  getNewLine: () => ts.sys.newLine,
};

function watchMain() {
  const configPath = ts.findConfigFile(/*searchPath*/ './', ts.sys.fileExists, 'tsconfig.json');
  if (!configPath) {
    throw new Error("Could not find a valid 'tsconfig.json'.");
  }

  // TypeScript can use several different program creation "strategies":
  //  * ts.createEmitAndSemanticDiagnosticsBuilderProgram,
  //  * ts.createSemanticDiagnosticsBuilderProgram
  //  * ts.createAbstractBuilder
  // The first two produce "builder programs". These use an incremental strategy
  // to only re-check and emit files whose contents may have changed, or whose
  // dependencies may have changes which may impact change the result of prior
  // type-check and emit.
  // The last uses an ordinary program which does a full type check after every
  // change.
  // Between `createEmitAndSemanticDiagnosticsBuilderProgram` and
  // `createSemanticDiagnosticsBuilderProgram`, the only difference is emit.
  // For pure type-checking scenarios, or when another tool/process handles emit,
  // using `createSemanticDiagnosticsBuilderProgram` may be more desirable.
  const createProgram = ts.createSemanticDiagnosticsBuilderProgram;

  // Note that there is another overload for `createWatchCompilerHost` that takes
  // a set of root files.
  const host = ts.createWatchCompilerHost(configPath, {}, ts.sys, createProgram, reportDiagnostic, reportWatchStatusChanged);

  // You can technically override any given hook on the host, though you probably
  // don't need to.
  // Note that we're assuming `origCreateProgram` and `origPostProgramCreate`
  // doesn't use `this` at all.
  const origCreateProgram = host.createProgram;
  host.createProgram = (rootNames, options, host, oldProgram) => {
    console.time('\033[0;32mCompiled\033[0m');
    return origCreateProgram(rootNames, options, host, oldProgram);
  };
  const origPostProgramCreate = host.afterProgramCreate;

  host.afterProgramCreate = (program) => {
    console.timeEnd('\033[0;32mCompiled\033[0m');
    origPostProgramCreate(program);
  };

  // `createWatchProgram` creates an initial program, watches files, and updates
  // the program over time.
  ts.createWatchProgram(host);
}

function reportDiagnostic(diagnostic) {
  console.error(
    '\033[0;31mError\033[0m',
    diagnostic.file.path,
    ':',
    ts.flattenDiagnosticMessageText(`${'\033[0;32m'}${JSON.stringify(diagnostic.messageText)}${'\033[0m'}`, formatHost.getNewLine()),
  );
}

/**
 * Prints a diagnostic every time the watch status changes.
 * This is mainly for messages like "Starting compilation" or "Compilation completed".
 */
let proc;
function reportWatchStatusChanged(diagnostic) {
  // Found 0 errors. Watching for file changes.
  if (diagnostic.code === 6194) {
    if (proc) {
      proc.kill();
    }
    const cmd = getCommand();
    const separatedCMD = cmd.split(' ');
    proc = spawn(separatedCMD[0], separatedCMD.slice(1));
    proc.stdout.on('data', (data) => {
      console.log(data.toString());
    });

    proc.stderr.on('data', (data) => {
      console.error(data.toString());
    });

    proc.on('close', (code) => {
      console.log(`child process exited with code ${code}`);
      process.exit(code);
    });
  }
  console.info(`${'\033[0;32m'}${ts.formatDiagnostic(diagnostic, formatHost)}${'\033[0m'}`);
}

process.on('SIGINT', () => {
  if (proc) {
    proc.kill();
  }
});

watchMain();

```
To try it out,  just execute this script like this:
```
node ts-watcher.js --onSuccess echo "I'm a command that is executed when the compilation succeed"
```
Let's extend this script to have all the functionalities tsc-watch already have and make it independent of the typescript version.

**Comment by gilamran** [comment]
Actually after solving several issue in this repo I found that not being depended on a specific typescript version, and using the "dump"/"easy" way and listen to the stdout is better.
There so many project types, new parameters on the typescript compiler, tsconfig.json issue and more...
Letting typescript deal with that is a lot simpler than handling it all by myself using the language services.

One of the examples is finding out the tsconfig.json, this alone will cause many issues to users that have special requirements.

I know, this is not very error prone and might break in future typescript versions.. but for now, the easy/dumb way works without any major issues. I'm afraid that complicating it will raise many problems...

WDYT?

**Comment by gilamran** [comment]
Issue was updated for several months, closing.
