### ISSUE TITLE
No ignore option

### ISSUE THREAD

**Issue by rm-rf-etc** [gilamran/tsc-watch#83]
The watcher gets stuck in a reload loop when trying to use this with `level` and use a data directory in the project root. It would help to be able to specify an ignore pattern.

**Comment by gilamran** [comment]
Sorry, I don't understand the issue.
Please share some more details.

**Comment by flcoder** [comment]
Basically, if you create a new directory like `./data` and add a file, tsc-watch reloads, is there a way to tell it to watch only specific dirs/files? or ignore specific dirs/files?

**Comment by gilamran** [comment]
`tsc-watch` is not doing the actual watch action, it's typescript itself. 
`tsc-watch` adds the `--watch` tag,  and run tasks on fail/successful compilation.

To ignore files, just add the directory to the `"exclude"` section in your `tsconfig.json`

Hope this helps.

**Comment by gilamran** [comment]
Bump.
Is this still an issue?

**Comment by Christilut** [comment]
Same problem here. I have a folder inside the working dir that my program adds files to and when it does that, a restart is triggered. I tried to exclude in the tsconfig but seems to have no effect. In my case they are not .ts files but other files like XML and such.

**Comment by gilamran** [comment]
@Christilut what happens when you just use `tsc --watch` ? is it re-triggering the build again?

**Comment by Christilut** [comment]
Yes it does.
I have this in my tsconfig:
```
  "include": [
    "**/*.ts"
  ],
```
And if I add an exclude it still rebuilds too:
```
  "exclude": [
    "./storage/**"
  ],
```

**Comment by gilamran** [comment]
I see your issue, but this is related to typesript itself...
maybe report an issue there?

**Comment by Christilut** [comment]
Okay will do, thanks! Must be something in the TS settings that I haven't figured out yet.
