### ISSUE TITLE
tsc-watch isn't compatible with Typescript Project References

### ISSUE THREAD

**Issue by moezbhatti** [gilamran/tsc-watch#84]
When running `tsc -w` with project references, I need to include the `-b` / `--build` flag so that project references are also compiled, and the compiler will be run whenever files in those local dependencies are refreshed as well. It doesn't seem that there's a way to include this flag in tsc-watch

**Comment by gilamran** [comment]
When you change a file in the reference project, do you see something on the console?

**Comment by gilamran** [comment]
Actually I just gave it a try on [this](https://github.com/RyanCavanaugh/project-references-demo) and it works great

**Comment by moezbhatti** [comment]
Hmm, very strange. When I tested it in my own project, there would be no console output when I changed a file in the referenced project. Works perfectly fine with `tsc -w- b` though

Did you just run `tsc-watch` or did you need to add some flags for it to work? And which directory did you run the command from?

**Comment by gilamran** [comment]
I just cloned the project that I mentioned above, and changed `tsc` to `tsc-watch` and added `--onSuccess node 1.js` and saw that `node 1.js` run on each file change.

Maybe you can create an example repo. with similar structure to your repo.? if it;s open-source event better share it with me.

This sound too important to miss.
Thanks

**Comment by moezbhatti** [comment]
Ah, I think I know why your test worked in your test, but not in my project. You were running `tsc-watch` at the project level, which will automatically compile all of the .ts in the entire repo

In my case I'm working with a monorepo, and when I'm running tsc, I'm running inside one of the specific packages that I'm working with. The benefit of `-b` is that if you compile a particular package that contains a project reference, tsc will know to compile the dependency first. But it will do this without compiling all of the other packages in your repo, it will only compile what it needs to

**Comment by moezbhatti** [comment]
A simple breakdown of the usecase for this is a project structure like this

```
/packages
  /backend
    /package.json
    /tsconfig.json
  /common
    /package.json
    /tsconfig.json
  /frontend
    /package.json
    /tsconfig.json
/package.json
/tsconfig.json
```
Both `frontend` and `backend` depend on the `common` package

I'm using webpack to package the frontend, so I never use tsc directly there

When I'm running my backend dev server, I run `tsc -b -w` in a script in `packages/backend/package.json`. If I replace `tsc -b -w` with `tsc-watch`, then it will only compile the `backend` source files, and not the `common` files. It will also only recompile when files in `backend` have changed, unlike when I use `tsc -b -w`

**Comment by gilamran** [comment]
In your `backend` `tsconfig.json` do you have reference to the `common` package?
In the root `tsconfig.json` do you have references to the `backend` and `common` ?
Why not run `tsc -b -w` in the root folder? it should compile only the `common` and `backend`
Anyway. But this should work in your way...

Actually this looks very similar to a starter kit that I created, take a look [here](https://github.com/gilamran/fullstack-typescript) it is working there

**Comment by moezbhatti** [comment]
That's correct, I do. My root `tsconfig.json` also has a reference to `frontend`

The reason I'm not running it in the root folder is because `frontend` also has its own `tsconfig.json`, but I don't want `tsc` to touch it directly, as its compilation is handled by webpack

**Comment by gilamran** [comment]
Why do you need the `frontend` in the root, if it's not used from outside?
Can you try and create a repo. showing the problem?
I can't seem to reproduce this.

**Comment by moezbhatti** [comment]
It needs to be part of the same repo because it depends on `common`. I can try to create a test repo when I get a chance, but realistically it won't be any different from this: https://github.com/gilamran/tsc-watch/issues/84#issuecomment-615449535

**Comment by gilamran** [comment]
Invited you to: [https://github.com/gilamran/test-tsc-watch](https://github.com/gilamran/test-tsc-watch), I've started your structure there.

**Comment by moezbhatti** [comment]
Thanks, I really appreciate your dedication to this. I'll check that out today!

**Comment by gilamran** [comment]
So, anything new regarding this issue?

**Comment by wistoft** [comment]
It works for my project. I have a script in: `packages/dev/server.ts`

A `package.json` entry along the lines of:

`"tscWatch": "tsc-watch -b packages/dev/tsconfig.json --onSuccess \"node dist/dev/server.js\"",`

`tsc` needs a `-b` switch to activate project references.

**Comment by dbousamra** [comment]
Beautiful
