### ISSUE TITLE
tsc-watch compiles/starts 2x/change and ramp-up is slow

### ISSUE THREAD

**Issue by desmap** [gilamran/tsc-watch#85]
`"dev": "tsc-watch --noClear --onSuccess \"node dist\""` compiles and starts always 2x/change. When replacing `node` by `nodemon` and `--onSuccess` by `--onFirstSuccess` it compiles and starts properly once per change. But even then it feels sluggish.

FWIW, meanwhile, I use `"dev": "concurrently \"tsc -w\"  \"nodemon dist\""` which works properly (1x compile & start/change) and is quite snappy.

**Comment by gilamran** [comment]
Sorry, I don't understand what is the problem and what you mean by 2x/change

**Comment by desmap** [comment]
Thanks for the quick response.

On file change tsc-watch compiles and starts the app two times. IDK how I can describe it better. It just does everything two times.

More infos: in tsconfig I specified  `"include": ["src/**/*"]` and my outDir is ./dist and I run the whole thing I a Docker container.

**Comment by gilamran** [comment]
You are probably doing something wrong, it doesn't suppose to do it twice for sure.
I'll need you to provide, your setup, like folder structure, package.json, anything that will allow me to reproduce this.

**Comment by desmap** [comment]
Thanks for your support! Since I switched already to concurrently + nodemon I would need to go back. I could do this the later the day. I really tinkered with tsc-watch few hours and couldn't get it working properly and fast.

Maybe you just try my solution and compare output and speed with your solution in a Docker container (until I can try tsc-watch again) and you might find the issue with tsc-watch yourself.

**Comment by desmap** [comment]
didnt test it but maybe helpful for you: if sourceMap is true, always to build files are generated and hence your lib is doing everything twice while nodemon has a default delay of 1sec before it restarts and hence just restarts once. maybe it's that??

**Comment by desmap** [comment]
here man, fyi, you get even more control on tsc's watch technique (tldr default fswatch is unreliable):

https://www.typescriptlang.org/docs/handbook/configuring-watch.html

I just testing eg RecursiveDirectoryUsingDynamicPriorityPolling and things get even faster!

**Comment by gilamran** [comment]
Regarding "fswatch is unreliable", I will test it.

Regarding your problem, the source maps shouldn't cause any issue... I'm using typescript to detect compilation complete, and then just run the `onSuccess` command.
There's no need for `nodemon` when using `tsc-watch`

I still don't understand how to reproduce your problem... I need some way to see that happen... maybe just create a repo.? allow me to see your repo.? share your setup? something...
I'm shooting here in the dark

**Comment by gilamran** [comment]
Maybe you are allowing typescript `js` files, and typescript is also "looking" into the `dist` folder and then detects new files there because of its own compilation?

**Comment by desmap** [comment]
sorry that I haven't come back yet, I remember that the compilation steps are caused by a file and a directory compile trigger which again do not happen with nodemon because you have an default delay of 1 sec. i try to setup an example repo hopefully next week

**Comment by gilamran** [comment]
Hi, did you test your issue?
* I don't want to leave orphan issues open.

**Comment by hillaryan** [comment]
@gilamran I ran into this issue as well. Here is how I would describe it with my project:

When the ts target is set to "es2017", every change causes the compiler to run once.
When the ts target is set to "es2019", every change causes the compiler to run twice. The first run is brief (<1s) and is cut short by the second run, which completes successfully.

**Comment by hillaryan** [comment]
@desmap Removing `tsc-watch` and directly running `tsc -watch` shows the same double run. So the problem has nothing to do with this package.

**Comment by gilamran** [comment]
@hillaryan Thanks for the update and the issue follow.

**Comment by CanTheAlmighty** [comment]
Same issue, rolling back to Typescript 4.8.4 solves the issue in the meantime

**Comment by gilamran** [comment]
Looks like this issue was closed, is this still happening for you on the latest typescript?
