### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by eMarek** [gilamran/tsc-watch#88]
Runing `tsc-watch` on version 4.2.4 returns this error and nothing happens afterwards:
```
env: node\r: No such file or directory
```
Any idea what is happening? On version 4.2.3 everything works all right.

**Comment by gilamran** [comment]
This happened before, checking

**Comment by gilamran** [comment]
release version 4.2.5, can you test?

**Comment by eMarek** [comment]
Better. Thanks for quickfix.
