### ISSUE TITLE
the SIG prefix is not valid according to the POSIX standard 

### ISSUE THREAD

**Issue by Asarew** [gilamran/tsc-watch#90]
This is the same issue that is discussed here: remy/nodemon#956

**Comment by gilamran** [comment]
You're saying that this: https://github.com/gilamran/tsc-watch/blob/master/lib/killer.js#L5
should change to `let KILL_SIGNAL = 'TERM';` ?

**Comment by Asarew** [comment]
No it should be `let KILL_SIGNAL = '15'; `

**Comment by gilamran** [comment]
I guess that this is a breaking change...

**Comment by Asarew** [comment]
No it will have the exact same effect across all Linux distroso

**Comment by gilamran** [comment]
Fixed on 4.2.6 (Minor version)
Thanks for the issue!

**Comment by Asarew** [comment]
No problem, Thanks for the quick support :+1:

**Comment by Asarew** [comment]
Could you make sure that the latest changes are also reflected in the master branch?

**Comment by gilamran** [comment]
sure.
