### ISSUE TITLE
Emit onCompilationRestart

### ISSUE THREAD

**Issue by wistoft** [gilamran/tsc-watch#94]
The feature request is simple. The client will emit an event, when `tsc` restarts compilation. This is useful, when needing to do something, when compiled files becomes invalid.

My specific use case is to graceful shutdown on windows, where you need to send an IPC message to the child. Processes will not respond to `SIGINT`, or any other thing, that I know of.

An alternative solution would be to support a `--graceful-ipc` flag as [node-dev](https://www.npmjs.com/package/node-dev)

**Comment by gilamran** [comment]
Sorry but I don't really understand your situation.
What do you want to do once the compilation started? shutdown windows??

**Comment by n8jadams** [comment]
Is there a programmatic way to restart tsc-watch? I've been using this very ugly hack to modify files and then remove the modification after a few ms. I think it's related to this issue.

**Comment by gilamran** [comment]
There's no programatic way to restart `tsc-watch` sry.
@n8jadams what is your use case?

**Comment by n8jadams** [comment]
@gilamran 
The use case is this

1. Edit graphql schema file
2. Nodemon watches that file change, and triggers copying it from src to dist directory
3. After the copying is done, we would like to trigger a server restart, so that updated version of the graphql schema file can be read in

**Comment by gilamran** [comment]
@n8jadams how is this related to typescript or tsc-watch?

**Comment by n8jadams** [comment]
The server is running with tsc-watch, so essentially I'm trying to use tsc-watch for running my server and watching typescript changes, and nodemon for watching non-typescript changes, generating/copying files, and then triggering tsc-watch to restart the server.

**Comment by gilamran** [comment]
This is a very specific use case, maybe you can do this with a script:
I can add the ability to "tell" tsc-watch to restart the `onSuccess` command. and in your script you can watch and copy the non-typescript changes. should be an easy implementation.

wdyt?

**Comment by n8jadams** [comment]
That sounds perfect.

**Comment by gilamran** [comment]
Well, totally forgot but this is actually already implemented on tsc-watch-client.
look at this example: https://github.com/gilamran/tsc-watch/blob/master/tsc-watch-client-example.js#L37
