### ISSUE TITLE
Cannot find module 'typescript/bin/tsc'

### ISSUE THREAD

**Issue by GCnomore** [gilamran/tsc-watch#98]
I just started to learn ts with tsc-watch and I'm stuck with this error message:

```
$ tsc-watch --onSuccess "node ./dist/index.js"
Cannot find module 'typescript/bin/tsc'
Require stack:
- C:\Users\isaac\Desktop\GC\test\test_typescript\node_modules\tsc-watch\lib\tsc-watch.js
- C:\Users\isaac\Desktop\GC\test\test_typescript\node_modules\tsc-watch\index.js
```

Below is my tsconfig.json
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "ES6",
    "sourceMap": true,
    "outDir": "dist"
  },
  "exclude": ["node_modules"],
  "include": ["src/**/*"]
}

```

I am a Windows user and my npm, node, tsc-watch are all up to date. 
Please help!

**Comment by gilamran** [comment]
Tpyescript is in the `peerDependencies` of `tsc-watch`
In order for it to use typescript, you also must install typescript.
just run `npm i typescript`

**Comment by GCnomore** [comment]
Hi gilamran, thank you for your reply but I did installed typescript globally before I ran tsc command.

**Comment by gilamran** [comment]
Installing TypeScript globally will not make it available for `tsc-watch`
`tsc-watch` is assuming that your project is using TypeScript internally.

**Comment by GCnomore** [comment]
Got it!
Thank you!!
