### ISSUE TITLE
Usage with tsc --build option

### ISSUE THREAD

**Issue by niklas-dahl** [gilamran/tsc-watch#99]
I am using project-references https://www.typescriptlang.org/docs/handbook/project-references.html and would like to reload my server if any of the referenced projects change.
Using `tsc --build --incremental --watch` already does everything I want, there is just no way to restart the server once tsc is done with a change.
As far as I understand https://github.com/microsoft/TypeScript/issues/29978 it should be possible.
But it seems that ts-node has not adopted the new APIs https://github.com/TypeStrong/ts-node/issues/817.

Is it possible with this tool to just pass the required flags to tsc?
Setting `build, incremental, watch` to `true` in the `tsconfig.json` does not work.

Thanks.

**Comment by gilamran** [comment]
Did you try:
`tsc-watch --build --incremental` (`--watch` is automatically added by tsc-watch)

**Comment by niklas-dahl** [comment]
Oh wow thanks, did actually not try that, it seems to work perfectly.

Just another small thing, piping the output like this `--onSuccess \"node js/index.js | pino-pretty -t -c\"` does not seem to work, I just get the regular output.

**Comment by gilamran** [comment]
The commands MUST be one command, you can run an npm command that does just that.

**Comment by niklas-dahl** [comment]
That works! Thanks.
